### ISSUE TITLE
如何实现我依赖的三方库也打包进去~

### ISSUE THREAD

**Issue by MIkeeJY** [top2015/fat-aar-2019#1]
RT

**Comment by high726** [comment]
在最终合并的module里 手动添加依赖

**Comment by MIkeeJY** [comment]
@top2015  我现在是把所有的module 单独打包合成一个aar 这个时候 每个module里依赖的三方库是无法打进去的，只有jar包可以，在最终合并的module里 手动添加依赖是怎么操作的？

**Comment by high726** [comment]
> @top2015 我现在是把所有的module 单独打包合成一个aar 这个时候 每个module里依赖的三方库是无法打进去的，只有jar包可以，在最终合并的module里 手动添加依赖是怎么操作的？

在打包工程的build.gradle文件重新依赖第三库，也就是说最终aar包括的文件只以你打包工程build.gradle的apt依赖为准
